### ISSUE TITLE
Tag 09 Fehlt

### ISSUE THREAD

**Issue by Odatas** [emrox/aoc-2022#1]
Denkst du du kannst meinem AOC Shittalk entkommen?

Tag 08 war gestern. Lets gooo.

**Comment by emrox** [comment]
I have no idea what you're talking about

**Comment by rbbl-dev** [comment]
Sir, this is a Wendy's

**Comment by stefan-evernest** [comment]
stop trolling, thx

**Comment by emrox** [comment]
stop trolling, thx
